### ISSUE TITLE
Cannot get gotoDate to work

### ISSUE THREAD

**Issue by Erdboden** [CroudTech/vue-fullcalendar#122]
i am passing config object with gotoDate field like so

` config: {
                    gotoDate: moment()
              }`

and pass to vue-full-calendar
`<full-calendar :events="events" :header="header"
                           defaultView="month" :editable="false" :config="config"></full-calendar>`

I have a watcher that changes the gotoDate field
`watch: {
            vacations: {
                handler: function () {
                    this.events = [];
                    if (this.vacations.data.length > 1) {
                        this.events = this.vacations.data;
                        this.config.gotoDate = moment();
                    } else {
                        this.events[0] = this.vacations.data;
                        this.config.gotoDate = moment(this.events[0].start);
                    }
                },
                deep: true
            }
        }`
I tried to pass string date formatted as YYY-MM-DD still nothing happens, no errors.
What am I doing wrong?

**Comment by BrockReece** [comment]
So, unless I am mistaken, isn't [goToDate](https://fullcalendar.io/docs/gotoDate) a method and not something that can be effected in the config.

There are docs in the [readme](https://github.com/CroudTech/vue-fullcalendar#methods) on how to handle methods, but essentially you need to...

Add a `ref` attribute to your component

```html
<full-calendar ref="calendar" :events="events" :header="header" defaultView="month" :editable="false" :config="config"></full-calendar>
```

Call the following from your watcher
```js
this.$refs.calendar.fireMethod('gotoDate', moment())
```

Hope that helps?

**Comment by Erdboden** [comment]
Super fast reply, thank you worked perfectly

**Comment by BrockReece** [comment]
nps

**Comment by Nandishju** [comment]
> ```
> calendar
> ```

Still, it is not working for me.
Followed same, but not working
Please help me
