### ISSUE TITLE
Can't catch actions next or prev buttons

### ISSUE THREAD

**Issue by ManoogD** [CroudTech/vue-fullcalendar#127]
Hi. I'm sorry I'm writing here because I don't know where to write else. I tried to find somewhere or somehow how to get action when there is click on next or prev buttons but didn't find anything. My problem is also described here https://stackoverflow.com/questions/50887335/vue-full-calendar-next-prev-buttons-trigger. Is there way to do this without jquery? Thanks.

**Comment by BrockReece** [comment]
Hi @ManoogD 

I'm not sure how familiar you are with Fullcalendar, you can define your events in a function ([see their docs](https://fullcalendar.io/docs/events-function)). This function will run every time the user presses the `next` and `prev` buttons or switches the view.

```js
config: {
  events(start, end, timezone, callback) {
    // do something
    callback(arrOfEvents)
  },
}
```

infact our main Readme shows an example of this technique for multiple event sources
https://github.com/CroudTech/vue-fullcalendar#using-a-json-feed

Does this help or was there something more specific you were after?

**Comment by ManoogD** [comment]
@BrockReece  Thank you for you response! Right now I did with eventSources and it works fine! I'm using websocket and in my project everyone who has subscribed to the topic should get notification as a event without refresh page. Now I get a single event and can't understand how to put in to array of exists events and render it.

**Comment by ManoogD** [comment]
ohhhh I GOT IT! if we use eventSources we also can push into the array. I thought if we use in array function we can't push to it anything. Ohhh it's so cool! Now it render from function events(start,end,etc), and after this I can push into this single event. THANK YOU

**Comment by BrockReece** [comment]
Ha, glad you sorted it out. I think I have just watched some first class rubber duck programming in action.

**Comment by DivingPigy** [comment]
Seems helpful for me!

**Comment by DivingPigy** [comment]
I solve the event problem, but timezone is disturbing me, I am in China, but timezone sets in America!
