### ISSUE TITLE
Selecting range issur after having scrolled the page

### ISSUE THREAD

**Issue by kbouh320** [CroudTech/vue-fullcalendar#128]
Hi,
I experience a strange issue when scrolling the page, when I do so I'm not able to select correctly a range, the selection is done but vertically offset by the distance of the page scroll.

I precise that it happens when the calendar height is greater than the window height.
Any clue?

Thanks

**Comment by BrockReece** [comment]
Hi @kbouh320 

No sorry, I've not seen this before. I will attempt to replicate it though.

**Comment by ibrahim-abde** [comment]
@kbouh320  I fixed the problem by downgrading the vue-full-calendar version to 3.0.0-0
and importing jquery myself `window.$ = require('jqury')`

**Comment by kbouh320** [comment]
@ibrahim-abde thanks for your help, unfortunately I now have this issue when using version 3.0.0-0

ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/vue-full-calendar/components/FullCalendar.vue
Module build failed: **ReferenceError: Unknown plugin "transform-runtime"** specified in "/Users/kevin/Development/simple/node_modules/vue-full-calendar/.babelrc" at 1, attempted to resolve relative to "/Users/kevin/Development/simple/node_modules/vue-full-calendar"

**Comment by BrockReece** [comment]
Sounds like a babel issue, try adding the `babel-plugin-transform-runtime` to your project.
```bash
npm install --save-dev babel-plugin-transform-runtime
# or yarn
yarn add babel-plugin-transform-runtime --dev
```

**Comment by kbouh320** [comment]
Thanks @BrockReece, I also had to change babel preset from stage-2 to es2015 but for the moment it doesn't affect the rest of the application

**Comment by doekenorg** [comment]
I'd like to reopen this issue as I think this is not wanted behavior. I'm getting the same issue, and while downgrading maybe a temporary solution, It would be nice if this could be fixed :)

**Comment by BrockReece** [comment]
@doekenorg I'm sorry about that, v4.0.0-0 is an alpha release for someone who requested to test out the new fullcalendar v4 alpha so the stable version of this lib is v2.6.0, I must have messed up the NPM publish if everyone is installing this alpha by default.

I also have #126 currently being tested which will do away with the need for babel.

**Comment by doekenorg** [comment]
Ah. That could help. Npm is showing 4.0.0-1 as current default. I'll try the correct stable tomorrow. Thanks for the quick response!

**Comment by BrockReece** [comment]
No worries, I will look into it to the default too.

**Comment by DivingPigy** [comment]
mark here

**Comment by DivingPigy** [comment]
@BrockReece Sir, I have a problem here, can you help me out ? https://github.com/CroudTech/vue-fullcalendar/issues/142

**Comment by BrockReece** [comment]
@DivingPigy do you have this issue too or was this just to point my attention at #142?
