### ISSUE TITLE
Can't use methods/computed to fill config props

### ISSUE THREAD

**Issue by GRUXXKi** [CroudTech/vue-fullcalendar#137]
Another problem with what I'm trying to do.

I'd like to be able to use some methods to build the config prop.

I've made an example here : https://codesandbox.io/s/n7v1vr8q80

For example if I use a defaultView who's computed by a 'methods' or 'computed ' the value is'nt send to the full calendar component.

Am I doing something wrong ?

**Comment by GRUXXKi** [comment]
Sorry this is a Vue normal behavior.

**Comment by DivingPigy** [comment]
Whar are you saying....................................
