### ISSUE TITLE
Component only works when registered via Vue.use()

### ISSUE THREAD

**Issue by mtimofiiv** [CroudTech/vue-fullcalendar#138]
Works like so:

```js
import Vue from 'vue';
import FullCalendar from 'vue-full-calendar';

Vue.use(FullCalendar);
```

```vue
<template>
  <full-calendar></full-calendar>
</template>
```

If you try to do this:

```vue
<template>
  <calendar></calendar>
</template>
<script>
import calendar from 'vue-full-calendar';

export default {
   components: {
     calendar
   }
}
</script>
```

You get `Failed to mount component: template or render function not defined`

**Comment by BrockReece** [comment]
Hey, the following should work...

```js
import { FullCalendar } from 'vue-full-calendar'
export default {
  components: {
    FullCalendar,
  },
}
```

**Comment by mtimofiiv** [comment]
@BrockReece tried that! Still having the issue. The name of the import does not seem to affect it.

**Comment by BrockReece** [comment]
@mtimofiiv this is working for me in this sandbox https://codesandbox.io/s/1zz00qvnzl

Btw, this isn't about the name of the import, this is specifically exporting the FullCalendar component as opposed from exporting the default Vue plugin.
```js
import { FullCalendar } from 'vue-full-calendar'
```

Hope that helps?

**Comment by mtimofiiv** [comment]
Sorry, misread that, did not notice the destructuring! Now it works.

**Comment by BrockReece** [comment]
Great
