### ISSUE TITLE
Any method for reload events?

### ISSUE THREAD

**Issue by DivingPigy** [CroudTech/vue-fullcalendar#142]
Hi!
I am feed the events by json feeding, as below:
`eventSources: [
        {
          events(start, end, timezone, callback) {
                var event_array = [];
                 // do something........
                callback(event_array);
              });
      ],`

Now, for some reason, I want to reload the events. Is there any method applicable for this question?
Thank you!

**Comment by DivingPigy** [comment]
`eventSources: [
        {
          events(start, end, timezone, callback) {

                var event_array = [];

                callback(event_array);
        },
      ],`

**Comment by DivingPigy** [comment]
Now, I am searching for some mechanism to reload the events. I worn out from the documentation by @event-refetch and so on.

**Comment by BrockReece** [comment]
@DivingPigy 

Whilst I appreciate your enthusiasm, can you calm down please. You are posting things faster than I can read them.

**Comment by BrockReece** [comment]
You should be able to fire the [refetchEvents](https://fullcalendar.io/docs/refetchEvents) which will refetch all of your event sources.

```js
this.$refs.calendar.fireMethod('refetchEvents')
```

Does that help?

**Comment by DivingPigy** [comment]
Let me try it again.

**Comment by DivingPigy** [comment]
Not work. I need to press F5 to reload the web page.

**Comment by DivingPigy** [comment]
Sir, can it be the consequense of the axios sequence?

**Comment by BrockReece** [comment]
I don't know. Can you tell me if there are any errors?

**Comment by DivingPigy** [comment]
Thank you for your reply, for some part, I am missed in docs.  
It is because of the sequence of axios. I ask for data before the axios reply.
A big lesson for me!

Thank you SIr!

**Comment by DivingPigy** [comment]
The code phase as bellow for new-commer like me, careful for the sequence:
![default](https://user-images.githubusercontent.com/26334368/42762488-141bbfdc-8943-11e8-93f1-4248ea2db933.png)

**Comment by BrockReece** [comment]
Just to clarify, this isn't anything specific to this lib. This is because `axios.post` is an async Promise so the events were being refetched before the new event was created.

**Comment by DivingPigy** [comment]
Yes， it is. A big lesson for me.
