### ISSUE TITLE
How can I force use fullcalendar v3.9.0?

### ISSUE THREAD

**Issue by Pulstarter** [CroudTech/vue-fullcalendar#144]
Hi!

I am having some issues with fullcalendar v4.0.0-alpha, so I need to fallback to 3.9.0. 

How can I archieve this?

Best regards

**Comment by BrockReece** [comment]
Try installing `vue-full-calendar@2.6.1`

**Comment by Pulstarter** [comment]
Thanks for the respense. I try with 3.0.0 and works fine now (fullcalendar 3.9.0)

Reading som other comments, I have the offset issue when you scroll the page, but It's an issue of v4, not from this package.

Best regards
