### ISSUE TITLE
Using vuex store as eventSources

### ISSUE THREAD

**Issue by stephiescastle** [CroudTech/vue-fullcalendar#148]
Hi, I'm fairly new to Vue, and I'm specifically using full calendar in Nuxt. 

I'm wondering if it's possible to use vuex store objects as eventSources. I got it working just using `:event="myStore" ` but I would like to use multiple store objects. So, for instance:

```
       eventSources: [
          myStore,
          myStore2,
          myStore3
        ],
```

Is this possible? BTW, I am using Vuex store in [Modules Mode](https://nuxtjs.org/guide/vuex-store/#modules-mode).

**Comment by BrockReece** [comment]
If i have understood correctly, each source will be an array of event objects that is stored in Vuex?
That should work, I don't see any reason why it wouldn't.
Let me know how you get on.
