### ISSUE TITLE
Problems about events request for different events types

### ISSUE THREAD

**Issue by DivingPigy** [CroudTech/vue-fullcalendar#150]
Hi!
      I used to solve the problem two weeks ago to reload event according to calendar-view change by "this.$refs.calendar.fireMethods('refetchEvents')".
      Now, the it is required to load events by condition outside the calendar. For example, reload events according to checkbox in parent component. I did this:
`<checkbox v-model="type.task" @change="eventReload">`
`eventReload(){`
`if(type.task){`
`this.$refs.calendar.fireMethod("refetchEvents");`
`}`
`// some logic `
`}`

Now, I have one question: If I click the the nav-links, is there some mechanism for reloading events according to the checkbox condition?

**Comment by DivingPigy** [comment]
I use json-feed, but can't access the data-member in data domain.

**Comment by DivingPigy** [comment]
Checkbox event can be easily to control the logic, nav-link can not attached to my logic.

**Comment by DivingPigy** [comment]
To config events for nav-links? 
![default](https://user-images.githubusercontent.com/26334368/43435372-4634d2c2-94b2-11e8-8ed4-3f7514699495.png)

**Comment by BrockReece** [comment]
What does your event fetching logic look like?

**Comment by DivingPigy** [comment]
Process according to condition. However, there should be a flag in your data element. For example, a property in your json object to help you to justify whether to process or skip the process. My logic as bellow:

![default](https://user-images.githubusercontent.com/26334368/43446519-afde31ae-94db-11e8-9f24-19b7df1edbfd.png)

Then, it work well for me!

Thank you for your kindly help!

**Comment by DivingPigy** [comment]
@BrockReece Sorry to forget @you

**Comment by BrockReece** [comment]
And what is not working in that logic?
