### ISSUE TITLE
Bug: Failed to resolve directive: el

### ISSUE THREAD

**Issue by kristoff2016** [CroudTech/vue-fullcalendar#155]
Hello, 
I got error: (found in <FullCalendar> at node_modules\vue-full-calendar\components\FullCalendar.vue)
this one:  ` <div v-el:calendar id="calendar"></div>`

Any ideas ?

thanks

**Comment by BrockReece** [comment]
What does your code look like?

**Comment by kristoff2016** [comment]
I used like this:  <full-calendar :config="config" :events="events"/>

**Comment by kristoff2016** [comment]
Because it is error this one: `v-el:calendar` 
my vue 2.5.7
thanks

**Comment by BrockReece** [comment]
Which version of `vue-full-calendar` are you using?
`v-el` isn't supported in vue 2, so we moved to use `v-ref` a while ago.

**Comment by kristoff2016** [comment]
Hello here is current version: ` "vue-full-calendar": "^2.6.1"`

**Comment by kristoff2016** [comment]
Yes, I saw it for this version:  `<div ref="calendar" id="calendar"></div>`
But New Error said:  
`build failed: Error: Couldn't find preset "stage-2" relative to directory "node_modules\\vue-full-calendar"`

I followed your instructions everything step by step.

thank you for your help

**Comment by kristoff2016** [comment]
![capture](https://user-images.githubusercontent.com/16773770/44578402-2df8ad00-a759-11e8-8a86-a01f2fb2b839.PNG)

**Comment by BrockReece** [comment]
How about installing `babel-preset-stage-2` through npm or yarn?

**Comment by kristoff2016** [comment]
Yes, it is fixed by instillation that one xD Thank you!
