### ISSUE TITLE
dayRender

### ISSUE THREAD

**Issue by mattkoch614** [CroudTech/vue-fullcalendar#156]
Is it possible to hook into the ``dayRender`` function using this package?

https://fullcalendar.io/docs/dayRender

I'd like to modify the color of a cell based on the date of the cell, and this function looks like a good way to do that.

**Comment by BrockReece** [comment]
You can add a callback for the `dayRender` event to the [custom config prop](https://github.com/CroudTech/vue-fullcalendar#custom-config) as I have done with the `drop` event in the readme.
