### ISSUE TITLE
how to use the method of changeview?have some demo?

### ISSUE THREAD

**Issue by dewdrops1** [CroudTech/vue-fullcalendar#159]

**Comment by steven87vt** [comment]
rread fullcalendars api guide on changeView to know what the method expects
[fullcalendar api on changeView](https://fullcalendar.io/docs/changeView)

vue-fullcalendar wiki has the example your looking for but didn't find here:
[direct method invocations using vue-fullcalendar](https://github.com/CroudTech/vue-fullcalendar#methods)

**Comment by BrockReece** [comment]
@steven87vt thanks for answering.

@dewdrops1 let me know if you need any further help.
