### ISSUE TITLE
Vue Full Calendar Event Select

### ISSUE THREAD

**Issue by Jochii12** [CroudTech/vue-fullcalendar#173]
Hello,
can i ask why my event select not trigger properly if there is 2 or more event in event

Thanks.. 
sample code
`
<template>
<full-calendar :config="config"
                       :event-sources="eventSources"
                       @event-created="createAppointment"
                       @event-selected="selectedAppointment"
                       ref="calendar"></full-calendar>

</template>

<script>
data: () => ({
eventSources : []
}),
methods:{
selectedAppointment(calEvent){
  //some methods
}
}
</script>
`

**Comment by BrockReece** [comment]
Hi @Jochii12 

I am not sure I understand the question.
What does your config object look like?

**Comment by Jochii12** [comment]
![image](https://user-images.githubusercontent.com/35551627/47989462-0aba8880-e120-11e8-90a9-157328fa454b.png)

![image](https://user-images.githubusercontent.com/35551627/47989519-2d4ca180-e120-11e8-944c-c9af43632ed6.png)

here my console object.. it return fine but it not rendering in my vuex

**Comment by Jochii12** [comment]
when i click the time 06: 00 it returning..
but when i click 09: its all null and in the console was fine

Thank you sir

**Comment by BrockReece** [comment]
I have tried to replicate this in a [code sandbox](https://codesandbox.io/s/88z24xkok2), but it seems to be emitting the `@event-selected` event for both of my calendar items, as I would expect.

**Comment by Jochii12** [comment]
i found sir.. one of the date is null so the vuex wont render the object date when is null. what i did is to use lodash and find the id on the array of object to fetch the select details.

`const data = _.find(this.appointSched, { id: calEvent.id })`
`var param = {
                    start: calEvent.start,
                    end: calEvent.end === null ? data.end : calEvent.end,
                    id: calEvent.id,
                    name: calEvent.title
                }`

**Comment by BrockReece** [comment]
Ok, glad you figured it out.
